# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
