# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-25 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180825_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='vendor_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
